### ISSUE TITLE
Userscript using MagicISRC - Apple Music Barcodes/ISRCs

### ISSUE THREAD

**Issue by ToadKing** [kepstin/magicisrc#11]
Submitting for https://magicisrc-beta.kepstin.ca/seeding.html

Script Homepage: https://github.com/ToadKing/apple-music-barcode-isrc

I've updated my userscript to use MagicISRC to submit ISRCs. Note that despite the `isrcM-T` format being preferred, I use the `isrcN` format. I've found that some digital versions of multi-disc releases often have conflicting media numbering on different digital services, thus different formats in MusicBrainz:

Example:

Apple Music: https://music.apple.com/us/album/final-fantasy-vii-remake-original-soundtrack/1513522478
MusicBrainz: https://musicbrainz.org/release/9bb970b5-31f2-456e-acea-2206c89b6ba9

The original physical release was on seven discs which Amazon and MusicBrainz use. Apple Music uses four mediums for some reason. Most other digital sites just use a single medium.

**Comment by kepstin** [comment]
Sorry for the delay :) It looks like your script is still being actively maintained, so I've added it to the list. It's visible [on the beta server](https://magicisrc-beta.kepstin.ca/seeding.html) right now, and i expect to update the main site soon.
